### PR TITLE
Add Info & Stats

### PR DESCRIPTION
**Pull request by pavansoundara**
- Implement bus info and stats
- Remove listenRandomPort() function as net.Listen() already provides that.

### CODE REVIEW

**Review by cjds — CHANGES_REQUESTED** [review]
Changes look good but can we add a few more tests?

**Comment by pavansoundara** [comment]
Yes, will add more tests covering the ros repo.

**Comment by cjds** [comment]
Tested on multiple node . @pavansoundara I'm going to merge this right now, and we can do a fix to add more tests to it.

**Comment by cjds** [comment]
@pavansoundara rebase and we get this in?

**Comment by pavansoundara** [comment]
This will be part of the actionlib PR.

**Pull request closed without merging**
